# 服务端口
server:
  port: 8202
  # 服务名
spring:
  application:
    name: service-cmn
  # 环境设置
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///yygh_cmn?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # 返回json的全局时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配制
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  # 设置mapper映射文件路径
  mapper-locations: classpath:com/atguigu/yygh/cmn/mapper/xml/*.xml
