#服务端口
server:
  port: 8205
spring:
  application:
    #服务名=service-oss
    name: service-oss
  profiles:
    #环境设置：dev、test、prod=dev
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  #阿里云 OSS
  #不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: your accessKeyId
      keysecret: your accessKeySecret
      # bucket可以在控制台创建，也可以使用java代码创建
      bucketname: syt-file-lucky845
